In [5]:
import pandas as pd


# dataset sera esta
dato1 = [1,2,2,3,4,4,5,6]
dato2 = [2,3,4,4,4,6,5,7]

m= 0.849
b= 1.504

diccionario = {"x": dato1, "y": dato2}

df= pd.DataFrame(diccionario)

df

   x  y
0  1  2
1  2  3
2  2  4
3  3  4
4  4  4
5  4  6
6  5  5
7  6  7

In [11]:
# Para realizar tabla de excel, para calcular ypred

df ["ypred"] = m * df.x + b

df

# Para realizar tabla de excel, para calcular y-ypred

df ["y-ypred"] = df.y - df.ypred

df

# Para realizar tabla de excel, para calcular ypred-y

df ["ypred-y"] = df.ypred - df.y

# Para realizar tabla de excel, para calcular ypred-y

df ["error2"] = df["ypred-y"] **2

df

   x  y  ypred  y-ypred  ypred-y    error2
0  1  2  2.353   -0.353    0.353  0.124609
1  2  3  3.202   -0.202    0.202  0.040804
2  2  4  3.202    0.798   -0.798  0.636804
3  3  4  4.051   -0.051    0.051  0.002601
4  4  4  4.900   -0.900    0.900  0.810000
5  4  6  4.900    1.100   -1.100  1.210000
6  5  5  5.749   -0.749    0.749  0.561001
7  6  7  6.598    0.402   -0.402  0.161604